server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 나중에 update로 바꿔야 함(처음에는 자동 생성을 위해서 넣어줌)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity(table)을 만들 때 변수명 그대로 필드명에 넣어줌
      use-new-id-generator-mappings: false # ID 생성할 때 JPA의 기본 전략을 따라가지 않음
    show-sql: true  # sql이 console에 남는 것
    properties:
      hibernate.format_sql: true # 원래 console에 한 줄로 나오는데 보기 좋게 나오게 함

  jackson:
    serialization:
      fail-on-empty-beans: false